import type { TipoRoupa } from './tipos';

/**
 * Catalogo de tipos de roupa.
 *
 * Escolhas por tras desta lista:
 *
 * - **Tipo, nunca produto.** Nenhuma marca, nenhum preco, nenhum link. Nada
 *   aqui esta a venda, e nada aqui envelhece quando uma colecao sai de linha.
 * - **Vocabulario brasileiro.** Os nomes e sinonimos sao os que se usa aqui
 *   ("rasteirinha", "chinelo slide", "calca pantalona"), e nao a traducao
 *   literal de catalogo estrangeiro.
 * - **Classificacao honesta.** Uma peca so recebe um estilo se ela realmente
 *   puxa para aquele lado. Marcar tudo como tudo faria o algoritmo de estilo
 *   aprender que todos os estilos sao iguais — e nao aprender nada.
 * - **Peca que quase todo mundo tem.** O catalogo cobre o guarda-roupa comum
 *   brasileiro, para a usuaria conseguir montar o dela na primeira sessao.
 *
 * Para acrescentar: manter o id em minusculas com hifen (`idRoupaSchema`) e
 * rodar `npx jest roupas` — ha teste conferindo id repetido, formato e
 * classificacao vazia.
 */
export const CATALOGO_ROUPAS: readonly TipoRoupa[] = [
  // ---------------------------------------------------------------- cima
  {
    id: 'camiseta-basica',
    nome: 'Camiseta básica',
    categoria: 'parte-de-cima',
    sinonimos: ['t-shirt', 'camiseta lisa', 'basica'],
    estilos: ['minimalista', 'classico', 'streetwear'],
    ocasioes: ['casual'],
    estacoes: ['verao', 'meia-estacao'],
    caimento: 'reto',
    descricao: 'A peça que combina com quase tudo. Serve sozinha ou por baixo.',
  },
  {
    id: 'camisa-social',
    nome: 'Camisa social',
    categoria: 'parte-de-cima',
    sinonimos: ['camisa de botão', 'camisa alfaiataria', 'camisete'],
    estilos: ['classico', 'minimalista'],
    ocasioes: ['trabalho', 'encontro'],
    estacoes: ['meia-estacao', 'inverno'],
    caimento: 'reto',
    descricao: 'Estrutura e seriedade. Fechada no trabalho, aberta como sobreposição.',
  },
  {
    id: 'camisa-linho',
    nome: 'Camisa de linho',
    categoria: 'parte-de-cima',
    sinonimos: ['camisa fresca', 'camisa de verão'],
    estilos: ['boho', 'minimalista', 'classico'],
    ocasioes: ['casual', 'praia'],
    estacoes: ['verao'],
    caimento: 'solto',
    descricao: 'Respira no calor e amassa sem parecer descuidada.',
  },
  {
    id: 'blusa-cropped',
    nome: 'Cropped',
    categoria: 'parte-de-cima',
    sinonimos: ['top cropped', 'blusa curta', 'cropped'],
    estilos: ['moderno', 'streetwear'],
    ocasioes: ['casual', 'festa'],
    estacoes: ['verao'],
    caimento: 'justo',
    descricao: 'Curta na cintura. Equilibra bem com peça de baixo alta.',
  },
  {
    id: 'regata-canelada',
    nome: 'Regata canelada',
    categoria: 'parte-de-cima',
    sinonimos: ['regata', 'blusa canelada', 'regatinha'],
    estilos: ['minimalista', 'moderno'],
    ocasioes: ['casual', 'praia'],
    estacoes: ['verao'],
    caimento: 'justo',
    descricao: 'Simples e ajustada. Some por baixo de qualquer sobreposição.',
  },
  {
    id: 'body-manga-longa',
    nome: 'Body de manga longa',
    categoria: 'parte-de-cima',
    sinonimos: ['body', 'collant'],
    estilos: ['moderno', 'minimalista'],
    ocasioes: ['festa', 'encontro', 'trabalho'],
    estacoes: ['meia-estacao', 'inverno'],
    caimento: 'justo',
    descricao: 'Nunca sai da saia nem da calça. Linha limpa o dia inteiro.',
  },
  {
    id: 'trico-gola-alta',
    nome: 'Tricô de gola alta',
    categoria: 'parte-de-cima',
    sinonimos: ['cacharrel', 'blusa de gola alta', 'suéter'],
    estilos: ['classico', 'minimalista'],
    ocasioes: ['trabalho', 'casual', 'encontro'],
    estacoes: ['inverno'],
    caimento: 'justo',
    descricao: 'Aquece sem volume. Cabe embaixo de casaco sem apertar.',
  },
  {
    id: 'camisa-jeans',
    nome: 'Camisa jeans',
    categoria: 'parte-de-cima',
    sinonimos: ['camisa de brim'],
    estilos: ['classico', 'streetwear'],
    ocasioes: ['casual'],
    estacoes: ['meia-estacao'],
    caimento: 'solto',
    descricao: 'Meio blusa, meio casaco. Resolve o dia que não decide a temperatura.',
  },
  {
    id: 'blusa-ombro-a-ombro',
    nome: 'Blusa ombro a ombro',
    categoria: 'parte-de-cima',
    sinonimos: ['ciganinha', 'blusa ciganinha'],
    estilos: ['romantico', 'boho'],
    ocasioes: ['encontro', 'casual', 'praia'],
    estacoes: ['verao'],
    caimento: 'solto',
    descricao: 'Deixa o ombro à mostra sem precisar de alça.',
  },
  {
    id: 'top-esportivo',
    nome: 'Top esportivo',
    categoria: 'parte-de-cima',
    sinonimos: ['top de treino', 'sutiã esportivo', 'top fitness'],
    estilos: ['esportivo'],
    ocasioes: ['academia'],
    estacoes: ['verao', 'meia-estacao'],
    caimento: 'justo',
    descricao: 'Sustentação para treinar. Nível de impacto muda por modalidade.',
  },
  {
    id: 'camisa-polo',
    nome: 'Camisa polo',
    categoria: 'parte-de-cima',
    sinonimos: ['polo'],
    estilos: ['classico', 'esportivo'],
    ocasioes: ['casual', 'trabalho'],
    estacoes: ['verao', 'meia-estacao'],
    caimento: 'reto',
    descricao: 'Um degrau acima da camiseta, sem chegar na camisa.',
  },
  {
    id: 'blusa-seda',
    nome: 'Blusa de seda',
    categoria: 'parte-de-cima',
    sinonimos: ['blusa fluida', 'blusa acetinada', 'blusa de cetim'],
    estilos: ['classico', 'romantico'],
    ocasioes: ['trabalho', 'festa', 'encontro'],
    estacoes: ['meia-estacao'],
    caimento: 'solto',
    descricao: 'Cai em vez de marcar. Levanta o look mais simples.',
  },
  {
    id: 'moletom-capuz',
    nome: 'Moletom com capuz',
    categoria: 'parte-de-cima',
    sinonimos: ['blusa de moletom', 'hoodie', 'casaco de moletom'],
    estilos: ['streetwear', 'esportivo'],
    ocasioes: ['casual', 'academia'],
    estacoes: ['meia-estacao', 'inverno'],
    caimento: 'oversized',
    descricao: 'Conforto assumido. Ganha forma com peça de baixo mais justa.',
  },
  {
    id: 'bata-boho',
    nome: 'Bata',
    categoria: 'parte-de-cima',
    sinonimos: ['túnica', 'bata longa'],
    estilos: ['boho', 'romantico'],
    ocasioes: ['praia', 'casual'],
    estacoes: ['verao'],
    caimento: 'solto',
    descricao: 'Comprida e larga, com bordado ou babado. Não pede cintura.',
  },

  // -------------------------------------------------------------- baixo
  {
    id: 'calca-jeans-skinny',
    nome: 'Calça jeans skinny',
    categoria: 'parte-de-baixo',
    sinonimos: ['jeans justo', 'calça justa', 'skinny'],
    estilos: ['classico', 'moderno'],
    ocasioes: ['casual', 'encontro'],
    estacoes: ['meia-estacao', 'inverno'],
    caimento: 'justo',
    descricao: 'Marca a perna inteira. Pede parte de cima mais solta.',
  },
  {
    id: 'calca-wide-leg',
    nome: 'Calça wide leg',
    categoria: 'parte-de-baixo',
    sinonimos: ['calça larga', 'pantalona', 'calça boca larga'],
    estilos: ['moderno', 'minimalista'],
    ocasioes: ['trabalho', 'casual'],
    estacoes: ['meia-estacao', 'verao'],
    caimento: 'solto',
    descricao: 'Larga do quadril ao pé. Alonga quando a cintura é alta.',
  },
  {
    id: 'calca-alfaiataria',
    nome: 'Calça de alfaiataria',
    categoria: 'parte-de-baixo',
    sinonimos: ['calça social', 'calça de trabalho'],
    estilos: ['classico', 'minimalista'],
    ocasioes: ['trabalho', 'festa'],
    estacoes: ['meia-estacao', 'inverno'],
    caimento: 'reto',
    descricao: 'Vinco e estrutura. A base do guarda-roupa de escritório.',
  },
  {
    id: 'legging',
    nome: 'Legging',
    categoria: 'parte-de-baixo',
    sinonimos: ['calça de treino', 'legging fitness', 'calça colada'],
    estilos: ['esportivo'],
    ocasioes: ['academia', 'casual'],
    estacoes: ['verao', 'meia-estacao', 'inverno'],
    caimento: 'justo',
    descricao: 'Segunda pele para treinar. Cintura alta segura no movimento.',
  },
  {
    id: 'saia-midi-plissada',
    nome: 'Saia midi plissada',
    categoria: 'parte-de-baixo',
    sinonimos: ['saia plissada', 'saia midi', 'saia pregueada'],
    estilos: ['romantico', 'classico'],
    ocasioes: ['trabalho', 'encontro', 'festa'],
    estacoes: ['meia-estacao'],
    caimento: 'solto',
    descricao: 'Roda ao andar e cobre até a canela. Formal sem ser dura.',
  },
  {
    id: 'saia-lapis',
    nome: 'Saia lápis',
    categoria: 'parte-de-baixo',
    sinonimos: ['saia justa', 'saia tubinho'],
    estilos: ['classico', 'moderno'],
    ocasioes: ['trabalho', 'festa'],
    estacoes: ['meia-estacao'],
    caimento: 'justo',
    descricao: 'Reta e ajustada até o joelho. Silhueta clássica de escritório.',
  },
  {
    id: 'saia-jeans',
    nome: 'Saia jeans',
    categoria: 'parte-de-baixo',
    sinonimos: ['saia de brim'],
    estilos: ['streetwear', 'moderno'],
    ocasioes: ['casual'],
    estacoes: ['verao', 'meia-estacao'],
    caimento: 'reto',
    descricao: 'Resistente e sem cerimônia. Vai do curto ao midi.',
  },
  {
    id: 'short-alfaiataria',
    nome: 'Short de alfaiataria',
    categoria: 'parte-de-baixo',
    sinonimos: ['short social', 'bermuda alfaiataria'],
    estilos: ['moderno', 'minimalista'],
    ocasioes: ['trabalho', 'casual'],
    estacoes: ['verao'],
    caimento: 'reto',
    descricao: 'A calça de alfaiataria em versão de calor.',
  },
  {
    id: 'short-jeans',
    nome: 'Short jeans',
    categoria: 'parte-de-baixo',
    sinonimos: ['shortinho', 'short de brim'],
    estilos: ['streetwear', 'boho'],
    ocasioes: ['casual', 'praia'],
    estacoes: ['verao'],
    caimento: 'reto',
    descricao: 'O básico do verão brasileiro. Combina com quase toda blusa.',
  },
  {
    id: 'calca-cargo',
    nome: 'Calça cargo',
    categoria: 'parte-de-baixo',
    sinonimos: ['calça de bolsos', 'cargo'],
    estilos: ['streetwear', 'esportivo'],
    ocasioes: ['casual'],
    estacoes: ['meia-estacao'],
    caimento: 'solto',
    descricao: 'Bolsos grandes na lateral. Peso urbano no look inteiro.',
  },
  {
    id: 'calca-pantalona-linho',
    nome: 'Calça pantalona de linho',
    categoria: 'parte-de-baixo',
    sinonimos: ['calça de linho', 'calça fresca'],
    estilos: ['boho', 'minimalista'],
    ocasioes: ['praia', 'casual'],
    estacoes: ['verao'],
    caimento: 'solto',
    descricao: 'Cobre a perna inteira sem esquentar. Ideal para litoral.',
  },
  {
    id: 'bermuda-ciclista',
    nome: 'Bermuda ciclista',
    categoria: 'parte-de-baixo',
    sinonimos: ['ciclista', 'short de lycra'],
    estilos: ['esportivo', 'streetwear'],
    ocasioes: ['academia', 'casual'],
    estacoes: ['verao'],
    caimento: 'justo',
    descricao: 'Colada e curta. Nasceu no treino e ficou na rua.',
  },

  // ------------------------------------------------------------ vestido
  {
    id: 'vestido-midi-fluido',
    nome: 'Vestido midi fluido',
    categoria: 'vestido',
    sinonimos: ['vestido soltinho', 'vestido midi'],
    estilos: ['romantico', 'boho'],
    ocasioes: ['encontro', 'festa', 'casual'],
    estacoes: ['verao', 'meia-estacao'],
    caimento: 'solto',
    descricao: 'Resolve o look inteiro numa peça só. Roda sem marcar.',
  },
  {
    id: 'vestido-slip',
    nome: 'Slip dress',
    categoria: 'vestido',
    sinonimos: ['vestido de alcinha', 'vestido acetinado', 'vestido lingerie'],
    estilos: ['moderno', 'romantico'],
    ocasioes: ['festa', 'encontro'],
    estacoes: ['verao'],
    caimento: 'reto',
    descricao: 'Alcinha fina e caimento de cetim. Muda de tom com o casaco por cima.',
  },
  {
    id: 'vestido-camisa',
    nome: 'Vestido camisa',
    categoria: 'vestido',
    sinonimos: ['chemise', 'vestido chemisier'],
    estilos: ['classico', 'minimalista'],
    ocasioes: ['trabalho', 'casual'],
    estacoes: ['meia-estacao', 'verao'],
    caimento: 'reto',
    descricao: 'Botões da gola à barra. Com cinto vira outra peça.',
  },
  {
    id: 'vestido-longo-festa',
    nome: 'Vestido longo de festa',
    categoria: 'vestido',
    sinonimos: ['vestido de gala', 'vestido longo', 'vestido de madrinha'],
    estilos: ['romantico', 'classico'],
    ocasioes: ['festa'],
    estacoes: ['meia-estacao'],
    caimento: 'reto',
    descricao: 'Para casamento e formatura. Vai até o pé.',
  },
  {
    id: 'vestido-tubinho',
    nome: 'Vestido tubinho',
    categoria: 'vestido',
    sinonimos: ['tubinho', 'vestido justo'],
    estilos: ['classico', 'minimalista'],
    ocasioes: ['trabalho', 'festa'],
    estacoes: ['meia-estacao'],
    caimento: 'justo',
    descricao: 'Reto, na altura do joelho. O preto dele salva qualquer convite.',
  },
  {
    id: 'macacao-pantalona',
    nome: 'Macacão pantalona',
    categoria: 'vestido',
    sinonimos: ['macacão', 'jumpsuit', 'macaquinho longo'],
    estilos: ['moderno', 'boho'],
    ocasioes: ['festa', 'trabalho', 'encontro'],
    estacoes: ['verao', 'meia-estacao'],
    caimento: 'solto',
    descricao: 'Uma peça, look pronto. A perna larga faz o volume.',
  },
  {
    id: 'vestido-trico',
    nome: 'Vestido de tricô',
    categoria: 'vestido',
    sinonimos: ['vestido de malha', 'vestido de inverno'],
    estilos: ['minimalista', 'classico'],
    ocasioes: ['casual', 'trabalho'],
    estacoes: ['inverno'],
    caimento: 'justo',
    descricao: 'Aquece e veste em uma peça. Pede bota.',
  },
  {
    id: 'saida-de-praia',
    nome: 'Saída de praia',
    categoria: 'vestido',
    sinonimos: ['canga', 'kaftan', 'saída de banho'],
    estilos: ['boho'],
    ocasioes: ['praia'],
    estacoes: ['verao'],
    caimento: 'solto',
    descricao: 'Veste por cima do biquíni e sai da areia direto pro quiosque.',
  },

  // ------------------------------------------------------- sobreposicao
  {
    id: 'blazer-alfaiataria',
    nome: 'Blazer de alfaiataria',
    categoria: 'sobreposicao',
    sinonimos: ['blazer', 'paletó'],
    estilos: ['classico', 'minimalista'],
    ocasioes: ['trabalho', 'festa', 'encontro'],
    estacoes: ['meia-estacao', 'inverno'],
    caimento: 'reto',
    descricao: 'Deixa sério o que estiver por baixo, inclusive camiseta.',
  },
  {
    id: 'blazer-oversized',
    nome: 'Blazer oversized',
    categoria: 'sobreposicao',
    sinonimos: ['blazer largo', 'blazer masculino'],
    estilos: ['moderno', 'streetwear'],
    ocasioes: ['casual', 'trabalho'],
    estacoes: ['meia-estacao'],
    caimento: 'oversized',
    descricao: 'Ombro caído de propósito. Estrutura sem formalidade.',
  },
  {
    id: 'jaqueta-jeans',
    nome: 'Jaqueta jeans',
    categoria: 'sobreposicao',
    sinonimos: ['jaqueta de brim', 'jaquetinha jeans'],
    estilos: ['streetwear', 'classico'],
    ocasioes: ['casual', 'encontro'],
    estacoes: ['meia-estacao'],
    caimento: 'reto',
    descricao: 'Quebra a formalidade de vestido e saia. Nunca sai de moda.',
  },
  {
    id: 'trench-coat',
    nome: 'Trench coat',
    categoria: 'sobreposicao',
    sinonimos: ['casaco de chuva', 'sobretudo leve', 'trench'],
    estilos: ['classico'],
    ocasioes: ['trabalho', 'casual'],
    estacoes: ['inverno', 'meia-estacao'],
    caimento: 'solto',
    descricao: 'Comprido e com cinto. Segura chuva fina e arruma o look.',
  },
  {
    id: 'cardiga',
    nome: 'Cardigã',
    categoria: 'sobreposicao',
    sinonimos: ['casaquinho', 'cardigan', 'casaco de tricô'],
    estilos: ['romantico', 'classico'],
    ocasioes: ['trabalho', 'casual'],
    estacoes: ['meia-estacao', 'inverno'],
    caimento: 'solto',
    descricao: 'Abre e fecha na frente. O casaco de ar-condicionado.',
  },
  {
    id: 'colete-alfaiataria',
    nome: 'Colete de alfaiataria',
    categoria: 'sobreposicao',
    sinonimos: ['colete', 'colete social'],
    estilos: ['moderno', 'minimalista'],
    ocasioes: ['trabalho', 'festa'],
    estacoes: ['verao', 'meia-estacao'],
    caimento: 'justo',
    descricao: 'A estrutura do blazer sem a manga. Serve como blusa.',
  },
  {
    id: 'jaqueta-couro',
    nome: 'Jaqueta de couro',
    categoria: 'sobreposicao',
    sinonimos: ['perfecto', 'jaqueta biker', 'jaqueta de couro sintético'],
    estilos: ['streetwear', 'moderno'],
    ocasioes: ['festa', 'encontro', 'casual'],
    estacoes: ['inverno', 'meia-estacao'],
    caimento: 'justo',
    descricao: 'Endurece o que for delicado. Vestido fluido pede uma.',
  },
  {
    id: 'sobretudo',
    nome: 'Sobretudo',
    categoria: 'sobreposicao',
    sinonimos: ['casacão', 'casaco longo', 'maxi casaco'],
    estilos: ['classico', 'minimalista'],
    ocasioes: ['trabalho', 'festa'],
    estacoes: ['inverno'],
    caimento: 'solto',
    descricao: 'Casaco de lã até o joelho. Frio de verdade, sem perder a linha.',
  },
  {
    id: 'corta-vento',
    nome: 'Corta-vento',
    categoria: 'sobreposicao',
    sinonimos: ['jaqueta esportiva', 'windbreaker', 'blusa de corrida'],
    estilos: ['esportivo', 'streetwear'],
    ocasioes: ['academia', 'casual'],
    estacoes: ['meia-estacao'],
    caimento: 'solto',
    descricao: 'Leve, fecha o vento e cabe dobrado na bolsa.',
  },
  {
    id: 'kimono',
    nome: 'Kimono',
    categoria: 'sobreposicao',
    sinonimos: ['quimono', 'sobreposição fluida'],
    estilos: ['boho', 'romantico'],
    ocasioes: ['praia', 'casual', 'festa'],
    estacoes: ['verao'],
    caimento: 'solto',
    descricao: 'Aberto e fluido, com estampa. Dá movimento sem esquentar.',
  },

  // ------------------------------------------------------------ calcado
  {
    id: 'tenis-branco',
    nome: 'Tênis branco',
    categoria: 'calcado',
    sinonimos: ['tênis casual', 'tênis liso'],
    estilos: ['minimalista', 'classico', 'streetwear'],
    ocasioes: ['casual', 'trabalho'],
    estacoes: ['verao', 'meia-estacao', 'inverno'],
    caimento: 'reto',
    descricao: 'Vai com jeans, com vestido e com alfaiataria. O curinga.',
  },
  {
    id: 'tenis-chunky',
    nome: 'Tênis chunky',
    categoria: 'calcado',
    sinonimos: ['tênis de sola alta', 'dad shoe', 'tênis robusto'],
    estilos: ['streetwear', 'esportivo'],
    ocasioes: ['casual', 'academia'],
    estacoes: ['meia-estacao'],
    caimento: 'reto',
    descricao: 'Sola grossa e volume proposital. Puxa o look para a rua.',
  },
  {
    id: 'sandalia-tira-fina',
    nome: 'Sandália de tira fina',
    categoria: 'calcado',
    sinonimos: ['sandália de salto', 'sandália de festa'],
    estilos: ['romantico', 'moderno'],
    ocasioes: ['festa', 'encontro'],
    estacoes: ['verao'],
    caimento: 'justo',
    descricao: 'Quase invisível no pé. Alonga a perna sem pesar no look.',
  },
  {
    id: 'mule-bico-fino',
    nome: 'Mule bico fino',
    categoria: 'calcado',
    sinonimos: ['mule', 'sapato aberto atrás'],
    estilos: ['moderno', 'minimalista'],
    ocasioes: ['trabalho', 'encontro'],
    estacoes: ['meia-estacao'],
    caimento: 'justo',
    descricao: 'Fechado na frente, aberto atrás. Calça e descalça em segundos.',
  },
  {
    id: 'scarpin',
    nome: 'Scarpin',
    categoria: 'calcado',
    sinonimos: ['sapato de salto', 'scarpan'],
    estilos: ['classico'],
    ocasioes: ['trabalho', 'festa'],
    estacoes: ['meia-estacao'],
    caimento: 'justo',
    descricao: 'Fechado, salto médio ou alto. O sapato formal por definição.',
  },
  {
    id: 'rasteirinha',
    nome: 'Rasteirinha',
    categoria: 'calcado',
    sinonimos: ['sandália rasteira', 'sandália baixa'],
    estilos: ['boho', 'romantico'],
    ocasioes: ['casual', 'praia'],
    estacoes: ['verao'],
    caimento: 'reto',
    descricao: 'Sem salto e sem drama. O calçado do calor brasileiro.',
  },
  {
    id: 'bota-cano-curto',
    nome: 'Bota de cano curto',
    categoria: 'calcado',
    sinonimos: ['ankle boot', 'botinha', 'coturno baixo'],
    estilos: ['moderno', 'classico'],
    ocasioes: ['casual', 'trabalho', 'encontro'],
    estacoes: ['inverno', 'meia-estacao'],
    caimento: 'justo',
    descricao: 'Para no tornozelo. Fecha look de calça e de vestido.',
  },
  {
    id: 'bota-cano-alto',
    nome: 'Bota de cano alto',
    categoria: 'calcado',
    sinonimos: ['bota longa', 'over the knee', 'bota de cano longo'],
    estilos: ['moderno', 'streetwear'],
    ocasioes: ['festa', 'encontro'],
    estacoes: ['inverno'],
    caimento: 'justo',
    descricao: 'Sobe na perna e domina o look. Pede peça de baixo discreta.',
  },
  {
    id: 'mocassim',
    nome: 'Mocassim',
    categoria: 'calcado',
    sinonimos: ['loafer', 'sapato fechado sem salto'],
    estilos: ['classico', 'minimalista'],
    ocasioes: ['trabalho', 'casual'],
    estacoes: ['meia-estacao', 'inverno'],
    caimento: 'reto',
    descricao: 'Fechado, sem salto e sem cadarço. Conforto que passa por formal.',
  },
  {
    id: 'chinelo-slide',
    nome: 'Chinelo slide',
    categoria: 'calcado',
    sinonimos: ['slide', 'chinelo de tira', 'papete'],
    estilos: ['esportivo', 'streetwear'],
    ocasioes: ['praia', 'casual'],
    estacoes: ['verao'],
    caimento: 'reto',
    descricao: 'Tira larga e sola macia. Da piscina ao mercado.',
  },

  // -------------------------------------------------------------- bolsa
  {
    id: 'bolsa-tote',
    nome: 'Bolsa tote',
    categoria: 'bolsa',
    sinonimos: ['bolsa grande', 'sacola', 'bolsa de trabalho'],
    estilos: ['minimalista', 'classico'],
    ocasioes: ['trabalho', 'casual'],
    estacoes: ['verao', 'meia-estacao', 'inverno'],
    caimento: 'solto',
    descricao: 'Cabe notebook, garrafa e guarda-chuva. A bolsa do dia inteiro.',
  },
  {
    id: 'bolsa-baguete',
    nome: 'Bolsa baguete',
    categoria: 'bolsa',
    sinonimos: ['baguete', 'bolsa de ombro pequena'],
    estilos: ['moderno', 'streetwear'],
    ocasioes: ['casual', 'encontro'],
    estacoes: ['verao', 'meia-estacao'],
    caimento: 'justo',
    descricao: 'Pequena e colada no corpo, alça curta no ombro.',
  },
  {
    id: 'bolsa-transversal',
    nome: 'Bolsa transversal',
    categoria: 'bolsa',
    sinonimos: ['crossbody', 'bolsa a tiracolo', 'shoulder bag'],
    estilos: ['minimalista', 'esportivo'],
    ocasioes: ['casual', 'praia'],
    estacoes: ['verao', 'meia-estacao'],
    caimento: 'reto',
    descricao: 'Alça atravessada, mãos livres. A mais segura na rua.',
  },
  {
    id: 'clutch',
    nome: 'Clutch',
    categoria: 'bolsa',
    sinonimos: ['carteira de mão', 'bolsa de festa'],
    estilos: ['classico', 'romantico'],
    ocasioes: ['festa'],
    estacoes: ['meia-estacao'],
    caimento: 'justo',
    descricao: 'Cabe celular, cartão e batom. Vai na mão, sem alça.',
  },
  {
    id: 'mochila-urbana',
    nome: 'Mochila urbana',
    categoria: 'bolsa',
    sinonimos: ['mochila', 'mochila de couro'],
    estilos: ['streetwear', 'esportivo'],
    ocasioes: ['casual', 'academia', 'trabalho'],
    estacoes: ['verao', 'meia-estacao', 'inverno'],
    caimento: 'reto',
    descricao: 'Peso nas duas costas. Para quem anda de bicicleta ou metrô.',
  },

  // ---------------------------------------------------------- acessorio
  {
    id: 'cinto-couro',
    nome: 'Cinto de couro',
    categoria: 'acessorio',
    sinonimos: ['cinto', 'cinto de fivela'],
    estilos: ['classico', 'minimalista'],
    ocasioes: ['trabalho', 'casual'],
    estacoes: ['verao', 'meia-estacao', 'inverno'],
    caimento: 'justo',
    descricao: 'Marca a cintura e muda a silhueta de vestido e casaco.',
  },
  {
    id: 'lenco-seda',
    nome: 'Lenço de seda',
    categoria: 'acessorio',
    sinonimos: ['lenço', 'echarpe', 'foulard'],
    estilos: ['classico', 'romantico'],
    ocasioes: ['trabalho', 'encontro'],
    estacoes: ['meia-estacao'],
    caimento: 'solto',
    descricao: 'No pescoço, no cabelo ou na alça da bolsa. Traz a cor.',
  },
  {
    id: 'oculos-sol',
    nome: 'Óculos de sol',
    categoria: 'acessorio',
    sinonimos: ['óculos escuros', 'óculos'],
    estilos: ['moderno', 'classico'],
    ocasioes: ['casual', 'praia'],
    estacoes: ['verao', 'meia-estacao'],
    caimento: 'justo',
    descricao: 'Protege e define o rosto. O formato conversa com o do rosto.',
  },
  {
    id: 'chapeu-palha',
    nome: 'Chapéu de palha',
    categoria: 'acessorio',
    sinonimos: ['chapéu', 'chapéu de praia'],
    estilos: ['boho'],
    ocasioes: ['praia', 'casual'],
    estacoes: ['verao'],
    caimento: 'solto',
    descricao: 'Sombra no rosto e ar de férias mesmo na cidade.',
  },
  {
    id: 'brinco-argola',
    nome: 'Brinco de argola',
    categoria: 'acessorio',
    sinonimos: ['argola', 'brinco redondo'],
    estilos: ['moderno', 'streetwear'],
    ocasioes: ['casual', 'festa', 'encontro'],
    estacoes: ['verao', 'meia-estacao', 'inverno'],
    caimento: 'reto',
    descricao: 'Um par resolve o rosto quando o resto está simples.',
  },
  {
    id: 'colar-camadas',
    nome: 'Colar de camadas',
    categoria: 'acessorio',
    sinonimos: ['colar', 'mix de correntes', 'colares sobrepostos'],
    estilos: ['boho', 'romantico'],
    ocasioes: ['casual', 'encontro'],
    estacoes: ['verao', 'meia-estacao'],
    caimento: 'solto',
    descricao: 'Correntes de comprimentos diferentes. Preenche decote liso.',
  },
  {
    id: 'relogio-classico',
    nome: 'Relógio clássico',
    categoria: 'acessorio',
    sinonimos: ['relógio', 'relógio de pulso'],
    estilos: ['classico', 'minimalista'],
    ocasioes: ['trabalho', 'encontro'],
    estacoes: ['verao', 'meia-estacao', 'inverno'],
    caimento: 'justo',
    descricao: 'O acessório que passa seriedade sem dizer nada.',
  },
];
